# CircleCI 2.0 configuration file
# More details on https://circleci.com/docs/2.0/language-go/
version: 2.0
jobs:
  build_linux:
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout
      - run: ./go_unit_test.sh
      - run: bash <(curl -s https://codecov.io/bash)
      - run: make

workflows:
  version: 2
  build-workflow:
    jobs:
      - build_linux
